README.md

feat(readme)

---

config.template.toml
configs/reviewer_prompt.yaml
scripts/review.py
tiny_scientist/reviewer.py

Closes #73  
Reorg the reviewer.py. The current workflow is:
```
1. load the paper -> 2. generate a query -> 3. search related papers -> 4. review -> 5. (re_review) depends on the reflection_num, use the same related papers -> (repeat 2-5) depends on the reviews_num
```
Remove the fewshot feature

feat(reviewer): reorg reviewer

---

poetry.lock
pyproject.toml
scripts/review.py
scripts/think.py
tiny_scientist/reviewer.py
tiny_scientist/thinker.py

Closes # 
fix mypy errors in thinker.py, reviewer.py, review.py and think.py

fix(reviewer, thinker)mypy errors reviewer

---

README.md

fix(doc): fix readme instruction

---

configs/diagram_prompt.yaml
tiny_scientist/drawer.py

feat(drawer): support basic diagram drawer

---

configs/diagram_prompt.yaml
tests/test_scientist.py
tiny_scientist/__init__.py
tiny_scientist/drawer.py

feat(init): support more init for package release

---

scripts/code.py
scripts/demo.py
scripts/demo.sh
scripts/review.py
scripts/write.py
tiny_scientist/coder.py
tiny_scientist/reviewer.py
tiny_scientist/scientist.py
tiny_scientist/thinker.py
tiny_scientist/tool.py
tiny_scientist/writer.py

Closes #116  
Add config_dir argument. fix path in tool.py, it should access the config.toml correctly. Now it requires users to have "config.toml" by running 
```
cp config.template.toml config.toml
```

feat(thinker, reviewer, coder, tool): fix paths by adding config_dir

---

tiny_scientist/reviewer.py
tiny_scientist/thinker.py
tiny_scientist/tool.py
tiny_scientist/utils/loader.py
tiny_scientist/writer.py

feat(config): accelerate import speed

---

scripts/demo_deepseek.sh
tiny_scientist/coder.py
tiny_scientist/thinker.py

Closes # 
Add bash file for running demo using deepseek-reasoner. Since aider do not support deepseek-reasoner, modify it to use deepseek-coder instead.

feat(demo_deepseek, coder): add demo for deepseek-reasoner

---

config.template.toml
tiny_scientist/coder.py
tiny_scientist/configs.py
tiny_scientist/utils/llm.py
tiny_scientist/writer.py

Closes #115 
Add llm_api_key and change corresponding usage in utils/llm.py
- [] My code requires changes to the documentation

feat(config): add llm_api_key

---

scripts/code.py
scripts/code.sh
scripts/demo.py
scripts/demo.sh
scripts/demo_deepseek.sh
scripts/review.py
scripts/think.py
scripts/write.py
tests/test_scientist.py
tiny_scientist/coder.py
tiny_scientist/drawer.py
tiny_scientist/reviewer.py
tiny_scientist/scientist.py
tiny_scientist/thinker.py
tiny_scientist/tool.py
tiny_scientist/utils/llm.py
tiny_scientist/utils/output_formatter.py
tiny_scientist/writer.py

feat(var): change name of var to clarify

---

experiments/baseline_results.txt
experiments/experiment.py
experiments/experiment_results.txt
experiments/idea.json

fix(experiment): add missing experiment supporting writer script

---

scripts/demo.py
scripts/review.py
scripts/think.py
tiny_scientist/data.py
tiny_scientist/prompts/thinker_prompt.yaml
tiny_scientist/reviewer.py
tiny_scientist/scientist.py
tiny_scientist/thinker.py

Closes # 
Reconstruct the thinker class and reviewer class. Both should work properly by:
Thinker:
```
from tiny_scientist import TinyScientist
agent = TinyScientist(model='gpt-4o')
idea = agent.thinker.run("...")
print(idea)
```
Reviwer:
```
from tiny_scientist import TinyScientist
agent = TinyScientist(model='gpt-4o')
review = agent.reviewer.run("...")
print(review)
```

feat(reviewer, thinker): restructure reviewer, thinker

---

tiny_scientist/prompts/thinker_prompt.yaml
tiny_scientist/scientist.py
tiny_scientist/thinker.py

Closes # 
Thinker.run was returning different result to thinker.think. They now returning the same type of Json

fix(thinker): thinker run now returning ideal result

---

tiny_scientist/data.py
tiny_scientist/prompts/thinker_prompt.yaml
tiny_scientist/thinker.py

fix(thinker): fixed thinker.run not returning intent related idea

---

tiny_scientist/utils/input_formatter.py

Error handling feature for input_formatter when parsing fails
Closes #

fix(input_formatter): add error handling for formatter

---

experiments/experiment.py
experiments/idea.json
scripts/demo.py
tiny_scientist/coder.py
tiny_scientist/data.py
tiny_scientist/prompts/coder_prompt.yaml
tiny_scientist/prompts/writer_prompt.yaml
tiny_scientist/utils/output_formatter.py
tiny_scientist/writer.py

fix(coder, writer): adapt coder and writer to current pipeline

---

README.md

feat(readme): update baseline results

---

README.md

feat(readme): simplify the readme example

---

README.md

feat(readme): add citation in readme

---

README.md

feat(readme): update the example code

---

README.md

fix(readme): fix small errors in readme

---

tiny_scientist/coder.py
tiny_scientist/prompts/coder_prompt.yaml
tiny_scientist/prompts/writer_prompt.yaml
tiny_scientist/utils/bib_manager.py
tiny_scientist/utils/output_formatter.py
tiny_scientist/writer.py

fix(baseline): set baseline as optional input

---

tiny_scientist/reviewer.py
tiny_scientist/tool.py
tiny_scientist/utils/bib_manager.py
tiny_scientist/utils/error_handler.py
tiny_scientist/utils/input_formatter.py
tiny_scientist/utils/output_formatter.py
tiny_scientist/utils/water_marker.py

feat(formatter): add more rich printing

---

tiny_scientist/thinker.py
tiny_scientist/writer.py

fix(write): auto fill in baseline_results when empty

---

pyproject.toml

feat(poetry): prepare for the release of 0.0.2

---

README.md

feat(readme): update examples

---

README.md
scripts/write.py
tiny_scientist/coder.py
tiny_scientist/prompts/writer_prompt.yaml
tiny_scientist/utils/output_formatter.py
tiny_scientist/writer.py

fix(writer): support auto install pdflatex

---

scripts/search_code.py
tiny_scientist/thinker.py
tiny_scientist/tool.py

feat(tool, thinker): update interface of PaperSearchTool

---

scripts/write.py
tiny_scientist/coder.py
tiny_scientist/configs.py
tiny_scientist/data.py
tiny_scientist/prompts/drawer_prompt.yaml
tiny_scientist/prompts/writer_prompt.yaml
tiny_scientist/tool.py
tiny_scientist/utils/output_formatter.py
tiny_scientist/writer.py

feat(drawer): add drawer to writer

---

scripts/demo.py
tiny_scientist/data.py
tiny_scientist/prompts/thinker_prompt.yaml
tiny_scientist/scientist.py
tiny_scientist/thinker.py

feat(thinker): support ranking multi ideas

---

tiny_scientist/prompts/writer_prompt.yaml

feat(yaml): update writer_prompt.yaml

---

tiny_scientist/writer.py

feat(drawer): run drawer for introduction

---

tiny_scientist/scientist.py
tiny_scientist/thinker.py

fix(thinker, scientist): enable generating exp plan

---

README.md

feat(doc): add Q&A section for errors

---

tiny_scientist/prompts/writer_prompt.yaml

feat(yaml): update writer prompt

---

README.md
tiny_scientist/scientist.py
tiny_scientist/thinker.py

feat(doc): add Q&A section

---

tiny_scientist/prompts/writer_prompt.yaml

feat(yaml): update prompt for table format control

---

tiny_scientist/prompts/writer_prompt.yaml

feat(yaml): change to columnwidth

---

tiny_scientist/prompts/writer_prompt.yaml

feat(yaml): delete the additional table requirement

---

pyproject.toml
tiny_scientist/utils/llm.py

Reverts ulab-uiuc/tiny-scientist#192

Revert "Support function call & Togetherai"

---

tiny_scientist/utils/llm.py

fix(llm): not getting api key right

---

tiny_scientist/thinker.py

Closes # 
remove redundant ranking usage for frontend website consideration

fix(thinker): remove redundant ranking usage

---

tiny_scientist/thinker.py

Closes # 
Add two functions for show and custom ranking criteria

feat(thinker): add custom ranking criteria

---

frontend/src/components/TreePlotVisualization.jsx

feat(frontend): test key with enviro variab

---

pyproject.toml

feat(poetry): support 0.1.1

---

backend/app.py

fix(security): fix cwe-22 security error

---

tiny_scientist/utils/output_formatter.py

fix(utils): fix latex template download repo

---

README.md
backend/app.py
config.template.toml
examples/demo.py
examples/hf_auto_eval.py
tiny_scientist/budget_checker.py
tiny_scientist/coder.py
tiny_scientist/reviewer.py
tiny_scientist/scientist.py
tiny_scientist/thinker.py
tiny_scientist/utils/pricing.py
tiny_scientist/writer.py

feat(tiny_scientist): add budget control

---

examples/demo.py
tiny_scientist/coder.py
tiny_scientist/prompts/coder_prompt.yaml
tiny_scientist/reviewer.py
tiny_scientist/scientist.py

feat(reviewer): support tex_path
